# Generated by Django 4.2.5 on 2023-09-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizzatoreViaggi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='date',
            field=models.DateField(),
        ),
    ]
