# Generated by Django 4.2.5 on 2023-09-14 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizzatoreViaggi', '0002_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizzatoreViaggi.travel')),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('receiver', models.EmailField(max_length=64)),
                ('state', models.BooleanField(default=False)),
                ('Travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizzatoreViaggi.travel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=250)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizzatoreViaggi.travel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
