# Generated by Django 4.2.5 on 2023-09-20 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizzatoreViaggi', '0002_alter_stage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='description',
            field=models.CharField(max_length=128),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizzatoreViaggi.travel')),
            ],
        ),
    ]
