# Generated by Django 4.2.5 on 2023-09-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizzatoreViaggi', '0003_alter_customuser_email_alter_customuser_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='Travel',
            new_name='travel',
        ),
    ]
