# Generated by Django 4.2.5 on 2023-09-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizzatoreViaggi', '0004_alter_expense_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='name',
            new_name='name_stage',
        ),
    ]
